"""Agent module — Orchestrator and Worker implementations."""

from ultimate_coders.agent.orchestrator import Orchestrator
from ultimate_coders.agent.worker import Worker
from ultimate_coders.agent.types import (
    ChangeType,
    FileChange,
    OrchestratorConfig,
    Subtask,
    SubtaskResult,
    SubtaskStatus,
    Task,
    TaskStatus,
    WorkerInfo,
)
from ultimate_coders.agent.llm import LLMClient, LLMResponse, ToolCall, ToolDefinition
from ultimate_coders.agent.rate_limiter import (
    CircuitBreaker,
    CircuitState,
    ModelFallbackChain,
    RateLimiter,
    RateLimiterConfig,
    RequestPriority,
    RetryPolicy,
    TaskComplexity,
    TokenBucket,
)
from ultimate_coders.agent.conflict import (
    ConflictDetector,
    ConflictInfo,
    ConflictMarker,
    ConflictResolver,
    ConflictResult,
    EditIntent,
    EditType,
    LineRange,
    MergeResult,
    ResolutionTier,
)
from ultimate_coders.agent.sandbox import (
    AgentAdapter,
    AgentOutput,
    ClaudeCodeAdapter,
    CodexAdapter,
    ExecResult,
    NetworkMode,
    SandboxConfig,
    SandboxHandle,
    SandboxManager,
    TokenUsage,
    available_agents,
    create_adapter,
)

__all__ = [
    "Orchestrator",
    "Worker",
    "ChangeType",
    "FileChange",
    "OrchestratorConfig",
    "Subtask",
    "SubtaskResult",
    "SubtaskStatus",
    "Task",
    "TaskStatus",
    "WorkerInfo",
    "LLMClient",
    "LLMResponse",
    "ToolCall",
    "ToolDefinition",
    # Rate limiter
    "CircuitBreaker",
    "CircuitState",
    "ModelFallbackChain",
    "RateLimiter",
    "RateLimiterConfig",
    "RequestPriority",
    "RetryPolicy",
    "TaskComplexity",
    "TokenBucket",
    # Conflict detection
    "ConflictDetector",
    "ConflictInfo",
    "ConflictMarker",
    "ConflictResolver",
    "ConflictResult",
    "EditIntent",
    "EditType",
    "LineRange",
    "MergeResult",
    "ResolutionTier",
    # Sandbox
    "AgentAdapter",
    "AgentOutput",
    "ClaudeCodeAdapter",
    "CodexAdapter",
    "ExecResult",
    "NetworkMode",
    "SandboxConfig",
    "SandboxHandle",
    "SandboxManager",
    "TokenUsage",
    "available_agents",
    "create_adapter",
]
